version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    python-prod-dependencies:
      dependency-type: "production"
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
    python-dev-dependencies:
      dependency-type: "development"
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
