[tool.flake8]
max-line-length = 100
exclude = "airflow/webserver_config.py"

[tool.isort]
atomic = true
known_first_party = ["anp_sales_miner", "tests"]
known_third_party = ["airflow"]
line_length = 100
multi_line_output = 0
use_parentheses = true
combine_as_imports = true

[tool.pytest.ini_options]
filterwarnings =  [
    "ignore:pandas.*64Index is deprecated:FutureWarning",
    'once:.*stats\.stats.*:DeprecationWarning',
    "once:.*Version classes.*:DeprecationWarning",
]
