name: test
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PIP_ROOT_USER_ACTION: ignore
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install system dependencies
        run: sudo apt-get install python3-distutils python3 curl -y
      - name: Install pip
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
      - name: Install pip dependencies
        run: pipenv install --dev
      - name: Run flake8
        run: pipenv run flake8
      - name: Move tests fixtures
        run: sudo mkdir -p /var/anp_sales_miner/tests; sudo mv -t /var/anp_sales_miner/tests tests/fixtures
      - name: Run tests
        run: pipenv run python -m pytest
